version: "3.8"

services:
  api:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./server:/app
      - ./temp_videos:/app/temp_videos
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
